#!/usr/bin/env python3
import subprocess
import tempfile
from pathlib import Path

CASES = {
    "rtl-mux": ("""module mux2(input logic a,b,sel, output logic y); assign y=sel?b:a; endmodule""", """module tb; logic a,b,sel,y; mux2 dut(a,b,sel,y); initial begin a=0;b=0;sel=0;#1;if(y!==0)$fatal; a=0;b=1;sel=0;#1;if(y!==0)$fatal; a=0;b=1;sel=1;#1;if(y!==1)$fatal; a=1;b=0;sel=1;#1;if(y!==0)$fatal; $display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-counter": ("""module counter #(parameter WIDTH=8)(input logic clk,reset,output logic [WIDTH-1:0] count); always_ff @(posedge clk) if(reset) count<='0; else count<=count+1'b1; endmodule""", """module tb;logic clk=0,reset;logic[7:0]count;counter dut(clk,reset,count);always #1 clk=~clk;initial begin reset=1;@(posedge clk);#0.1;if(count!==0)$fatal;reset=0;@(posedge clk);#0.1;if(count!==1)$fatal;@(posedge clk);#0.1;if(count!==2)$fatal;reset=1;@(posedge clk);#0.1;if(count!==0)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-priority": ("""module priority_encoder(input logic[7:0] in,output logic[2:0] index,output logic valid);always_comb begin index=0;valid=0;for(integer i=0;i<8;i++)if(in[i])begin index=i;valid=1;end end endmodule""", """module tb;logic[7:0]in;logic[2:0]index;logic valid;priority_encoder dut(in,index,valid);initial begin in=0;#1;if(valid!==0)$fatal;in=8'b00101000;#1;if(valid!==1||index!==5)$fatal;in=8'b10001000;#1;if(valid!==1||index!==7)$fatal;in=8'b00000001;#1;if(valid!==1||index!==0)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-fifo": ("""module fifo #(parameter WIDTH=8,DEPTH=4)(input logic clk,reset,wr_en,rd_en,input logic[WIDTH-1:0]din,output logic[WIDTH-1:0]dout,output logic full,empty);logic[WIDTH-1:0]mem[0:DEPTH-1];integer count,wp,rp;assign empty=count==0;assign full=count==DEPTH;always_ff@(posedge clk)begin if(reset)begin count<=0;wp<=0;rp<=0;dout<='0;end else begin if(wr_en&&!full)begin mem[wp]<=din;wp<=(wp+1)%DEPTH;end if(rd_en&&!empty)begin dout<=mem[rp];rp<=(rp+1)%DEPTH;end case({wr_en&&!full,rd_en&&!empty})2'b10:count<=count+1;2'b01:count<=count-1;default:count<=count;endcase end end endmodule""", """module tb;logic clk=0,reset,wr_en,rd_en;logic[7:0]din,dout;logic full,empty;fifo dut(clk,reset,wr_en,rd_en,din,dout,full,empty);always #1 clk=~clk;initial begin reset=1;wr_en=0;rd_en=0;din=0;@(posedge clk);#0.1;if(!empty||full)$fatal;reset=0;din=8'hA5;wr_en=1;@(posedge clk);#0.1;if(empty)$fatal;din=8'h3C;@(posedge clk);#0.1;if(empty)$fatal;wr_en=0;rd_en=1;@(posedge clk);#0.1;if(dout!==8'hA5)$fatal;@(posedge clk);#0.1;if(dout!==8'h3C)$fatal;@(posedge clk);#0.1;if(!empty)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-shift-register": ("""module shift_reg #(parameter WIDTH=8)(input logic clk,reset,shift_en,din,output logic[WIDTH-1:0]dout);always_ff@(posedge clk)if(reset)dout<='0;else if(shift_en)dout<={dout[WIDTH-2:0],din};endmodule""", """module tb;logic clk=0,reset,shift_en,din;logic[7:0]dout;shift_reg dut(clk,reset,shift_en,din,dout);always #1 clk=~clk;initial begin reset=1;shift_en=0;din=0;@(posedge clk);#0.1;if(dout!==0)$fatal;reset=0;shift_en=1;din=1;@(posedge clk);#0.1;if(dout!==8'h01)$fatal;din=0;@(posedge clk);#0.1;if(dout!==8'h02)$fatal;@(posedge clk);#0.1;if(dout!==8'h04)$fatal;shift_en=0;din=1;@(posedge clk);#0.1;if(dout!==8'h04)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-edge-detector": ("""module edge_detector(input logic clk,reset,signal_in,output logic rise);logic prev;always_ff@(posedge clk)if(reset)begin prev<=0;rise<=0;end else begin rise<=signal_in&~prev;prev<=signal_in;end endmodule""", """module tb;logic clk=0,reset,signal_in,rise;edge_detector dut(clk,reset,signal_in,rise);always #1 clk=~clk;initial begin reset=1;signal_in=0;@(posedge clk);#0.1;if(rise!==0)$fatal;reset=0;@(posedge clk);#0.1;if(rise!==0)$fatal;signal_in=1;@(posedge clk);#0.1;if(rise!==1)$fatal;@(posedge clk);#0.1;if(rise!==0)$fatal;signal_in=0;@(posedge clk);#0.1;if(rise!==0)$fatal;signal_in=1;@(posedge clk);#0.1;if(rise!==1)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-arbiter": ("""module arbiter4(input logic[3:0]req,output logic[3:0]grant);always_comb begin grant=0;for(integer i=3;i>=0;i--)if(req[i]&&grant==0)grant[i]=1;end endmodule""", """module tb;logic[3:0]req,grant;arbiter4 dut(req,grant);initial begin req=0;#1;if(grant!==0)$fatal;req=4'b0001;#1;if(grant!==4'b0001)$fatal;req=4'b0101;#1;if(grant!==4'b0100)$fatal;req=4'b1011;#1;if(grant!==4'b1000)$fatal;req=4'b0110;#1;if(grant!==4'b0100)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-regfile": ("""module regfile4(input logic clk,reset,we,input logic[1:0]waddr,raddr1,raddr2,input logic[7:0]wdata,output logic[7:0]rdata1,rdata2);logic[7:0]regs[0:3];integer i;assign rdata1=regs[raddr1];assign rdata2=regs[raddr2];always_ff@(posedge clk)if(reset)for(i=0;i<4;i++)regs[i]<='0;else if(we)regs[waddr]<=wdata;endmodule""", """module tb;logic clk=0,reset,we;logic[1:0]waddr,raddr1,raddr2;logic[7:0]wdata,rdata1,rdata2;regfile4 dut(clk,reset,we,waddr,raddr1,raddr2,wdata,rdata1,rdata2);always #1 clk=~clk;initial begin reset=1;we=0;waddr=0;raddr1=0;raddr2=1;wdata=0;@(posedge clk);#0.1;if(rdata1!==0||rdata2!==0)$fatal;reset=0;we=1;waddr=2;wdata=8'h5A;@(posedge clk);#0.1;we=0;raddr1=2;raddr2=0;#1;if(rdata1!==8'h5A||rdata2!==0)$fatal;we=1;waddr=0;wdata=8'hC3;@(posedge clk);#0.1;we=0;raddr1=0;#1;if(rdata1!==8'hC3)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-lfsr": ("""module lfsr8(input logic clk,reset,enable,output logic[7:0]state);logic feedback;assign feedback=state[7]^state[5]^state[4]^state[3];always_ff@(posedge clk)if(reset)state<=8'h01;else if(enable)state<={state[6:0],feedback};endmodule""", """module tb;logic clk=0,reset,enable;logic[7:0]state;lfsr8 dut(clk,reset,enable,state);always #1 clk=~clk;initial begin reset=1;enable=0;@(posedge clk);#0.1;if(state!==8'h01)$fatal;reset=0;enable=1;@(posedge clk);#0.1;if(state!==8'h02)$fatal;@(posedge clk);#0.1;if(state!==8'h04)$fatal;@(posedge clk);#0.1;if(state!==8'h08)$fatal;@(posedge clk);#0.1;if(state!==8'h11)$fatal;enable=0;@(posedge clk);#0.1;if(state!==8'h11)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule"""),
    "rtl-clock-divider": ("""module clk_div #(parameter DIV=2)(input logic clk,reset,enable,output logic clk_out);integer count;always_ff@(posedge clk)if(reset)begin count<=0;clk_out<=0;end else if(enable)if(count==DIV-1)begin count<=0;clk_out<=~clk_out;end else count<=count+1;endmodule""", """module tb;logic clk=0,reset,enable,clk_out;clk_div dut(clk,reset,enable,clk_out);always #1 clk=~clk;initial begin reset=1;enable=0;@(posedge clk);#0.1;if(clk_out!==0)$fatal;reset=0;enable=1;@(posedge clk);#0.1;if(clk_out!==0)$fatal;@(posedge clk);#0.1;if(clk_out!==1)$fatal;@(posedge clk);#0.1;if(clk_out!==1)$fatal;@(posedge clk);#0.1;if(clk_out!==0)$fatal;enable=0;@(posedge clk);#0.1;if(clk_out!==0)$fatal;$display(\"HDLFORGE_PASS\");$finish;end endmodule""")
}

with tempfile.TemporaryDirectory() as d:
    root = Path(d)
    for name, (design, bench) in CASES.items():
        (root / "design.sv").write_text(design)
        (root / "tb.sv").write_text(bench)
        build = subprocess.run(["iverilog", "-g2012", "-s", "tb", "-o", str(root / "sim"), str(root / "design.sv"), str(root / "tb.sv")], capture_output=True, text=True)
        if build.returncode:
            raise SystemExit(f"{name}: compile failed\n{build.stderr}")
        sim = subprocess.run(["vvp", str(root / "sim")], capture_output=True, text=True)
        if sim.returncode or "HDLFORGE_PASS" not in sim.stdout:
            raise SystemExit(f"{name}: simulation failed\n{sim.stdout}{sim.stderr}")
        print(f"PASS {name}")
print("All 10 HDLForge RTL regressions passed.")
