import http from 'node:http'
import { execFile } from 'node:child_process'
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { promisify } from 'node:util'

const execFileAsync=promisify(execFile)
const PORT=process.env.PORT||8787
const BACKEND_PORT=8788
const MAX_SOURCE=20000
const TIMEOUT_MS=5000
const vhdlBenches={
'rtl-mux':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal a,b,sel,y: std_logic:='0'; begin dut: entity work.{{DUT}}(rtl) port map(a=>a,b=>b,sel=>sel,y=>y); process begin a<='0';b<='0';sel<='0';wait for 1 ns;assert y='0' report "mux case 1" severity failure; a<='0';b<='1';sel<='0';wait for 1 ns;assert y='0' report "mux case 2" severity failure;sel<='1';wait for 1 ns;assert y='1' report "mux case 3" severity failure;a<='1';b<='0';wait for 1 ns;assert y='0' report "mux case 4" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-counter':`library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all; entity tb is end; architecture sim of tb is signal clk,reset: std_logic:='0'; signal count: std_logic_vector(7 downto 0); begin dut: entity work.{{DUT}}(rtl) port map(clk=>clk,reset=>reset,count=>count);clk<=not clk after 1 ns;process begin reset<='1';wait until rising_edge(clk);wait for 0.1 ns;assert count=x"00" report "reset" severity failure;reset<='0';wait until rising_edge(clk);wait for 0.1 ns;assert count=x"01" report "increment 1" severity failure;wait until rising_edge(clk);wait for 0.1 ns;assert count=x"02" report "increment 2" severity failure;reset<='1';wait until rising_edge(clk);wait for 0.1 ns;assert count=x"00" report "second reset" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-priority':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal inp: std_logic_vector(7 downto 0):=(others=>'0');signal index: std_logic_vector(2 downto 0);signal valid: std_logic;begin dut: entity work.{{DUT}}(rtl) port map(inp,index,valid);process begin inp<=(others=>'0');wait for 1 ns;assert valid='0' report "zero input" severity failure;inp<="00101000";wait for 1 ns;assert valid='1' and index="101" report "priority 5" severity failure;inp<="10001000";wait for 1 ns;assert valid='1' and index="111" report "priority 7" severity failure;inp<="00000001";wait for 1 ns;assert valid='1' and index="000" report "priority 0" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-fifo':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal clk,reset,wr_en,rd_en: std_logic:='0';signal din,dout: std_logic_vector(7 downto 0);signal full,empty: std_logic;begin dut: entity work.{{DUT}}(rtl) port map(clk=>clk,reset=>reset,wr_en=>wr_en,rd_en=>rd_en,din=>din,dout=>dout,full=>full,empty=>empty);clk<=not clk after 1 ns;process begin reset<='1';wr_en<='0';rd_en<='0';din<=x"00";wait until rising_edge(clk);wait for 0.1 ns;assert empty='1' and full='0' report "reset flags" severity failure;reset<='0';din<=x"A5";wr_en<='1';wait until rising_edge(clk);din<=x"3C";wait until rising_edge(clk);din<=x"77";wait until rising_edge(clk);wr_en<='0';assert full='1' report "fifo should be full" severity failure;rd_en<='1';wait until rising_edge(clk);wait for 0.1 ns;assert dout=x"A5" report "fifo first data" severity failure;wait until rising_edge(clk);wait for 0.1 ns;assert dout=x"3C" report "fifo second data" severity failure;wait until rising_edge(clk);wait for 0.1 ns;assert dout=x"77" report "fifo third data" severity failure;wait until rising_edge(clk);wait for 0.1 ns;assert empty='1' report "fifo should be empty" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-shift-register':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal clk,reset,shift_en,din: std_logic:='0';signal dout: std_logic_vector(7 downto 0);begin dut: entity work.{{DUT}}(rtl) port map(clk=>clk,reset=>reset,shift_en=>shift_en,din=>din,dout=>dout);clk<=not clk after 1 ns;process begin reset<='1';wait until rising_edge(clk);wait for 0.1 ns;assert dout=x"00" report "reset" severity failure;reset<='0';shift_en<='1';din<='1';wait until rising_edge(clk);din<='0';wait until rising_edge(clk);wait until rising_edge(clk);wait for 0.1 ns;assert dout=x"04" report "shift sequence" severity failure;shift_en<='0';din<='1';wait until rising_edge(clk);wait for 0.1 ns;assert dout=x"04" report "hold" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-edge-detector':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal clk,reset,signal_in,rise: std_logic:='0';begin dut: entity work.{{DUT}}(rtl) port map(clk=>clk,reset=>reset,signal_in=>signal_in,rise=>rise);clk<=not clk after 1 ns;process begin reset<='1';signal_in<='0';wait until rising_edge(clk);wait for 0.1 ns;assert rise='0' report "reset" severity failure;reset<='0';signal_in<='1';wait until rising_edge(clk);wait for 0.1 ns;assert rise='1' report "first edge" severity failure;wait until rising_edge(clk);wait for 0.1 ns;assert rise='0' report "one cycle pulse" severity failure;signal_in<='0';wait until rising_edge(clk);signal_in<='1';wait until rising_edge(clk);wait for 0.1 ns;assert rise='1' report "second edge" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-arbiter':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal req,grant: std_logic_vector(3 downto 0):=(others=>'0');begin dut: entity work.{{DUT}}(rtl) port map(req=>req,grant=>grant);process begin req<="0000";wait for 1 ns;assert grant="0000" report "zero" severity failure;req<="1111";wait for 1 ns;assert grant="1000" report "highest priority" severity failure;req<="0011";wait for 1 ns;assert grant="0010" report "priority 1" severity failure;req<="1001";wait for 1 ns;assert grant="1000" report "priority 3" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-regfile':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal clk,reset,we: std_logic:='0';signal waddr,raddr1,raddr2: std_logic_vector(1 downto 0):=(others=>'0');signal wdata,rdata1,rdata2: std_logic_vector(7 downto 0):=(others=>'0');begin dut: entity work.{{DUT}}(rtl) port map(clk=>clk,reset=>reset,we=>we,waddr=>waddr,raddr1=>raddr1,raddr2=>raddr2,wdata=>wdata,rdata1=>rdata1,rdata2=>rdata2);clk<=not clk after 1 ns;process begin reset<='1';wait until rising_edge(clk);wait for 0.1 ns;assert rdata1=x"00" and rdata2=x"00" report "reset clear" severity failure;reset<='0';we<='1';waddr<="10";wdata<=x"5A";wait until rising_edge(clk);we<='0';raddr1<="10";raddr2<="00";wait for 1 ns;assert rdata1=x"5A" and rdata2=x"00" report "async readback" severity failure;waddr<="01";wdata<=x"A6";we<='1';wait until rising_edge(clk);we<='0';raddr1<="01";raddr2<="10";wait for 1 ns;assert rdata1=x"A6" and rdata2=x"5A" report "two reads" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-lfsr':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal clk,reset,enable: std_logic:='0';signal state: std_logic_vector(7 downto 0);begin dut: entity work.{{DUT}}(rtl) port map(clk=>clk,reset=>reset,enable=>enable,state=>state);clk<=not clk after 1 ns;process begin reset<='1';wait until rising_edge(clk);wait for 0.1 ns;assert state=x"01" report "seed" severity failure;reset<='0';enable<='1';for i in 1 to 4 loop wait until rising_edge(clk);end loop;wait for 0.1 ns;assert state=x"11" report "sequence" severity failure;enable<='0';wait until rising_edge(clk);wait for 0.1 ns;assert state=x"11" report "enable hold" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`,
'rtl-clock-divider':`library ieee; use ieee.std_logic_1164.all; entity tb is end; architecture sim of tb is signal clk,reset,enable,clk_out: std_logic:='0';begin dut: entity work.{{DUT}}(rtl) port map(clk=>clk,reset=>reset,enable=>enable,clk_out=>clk_out);clk<=not clk after 1 ns;process begin reset<='1';enable<='0';wait until rising_edge(clk);wait for 0.1 ns;assert clk_out='0' report "reset" severity failure;reset<='0';enable<='1';wait until rising_edge(clk);wait for 0.1 ns;assert clk_out='0' report "edge 1" severity failure;wait until rising_edge(clk);wait for 0.1 ns;assert clk_out='0' report "edge 2" severity failure;wait until rising_edge(clk);wait for 0.1 ns;assert clk_out='1' report "edge 3 toggle" severity failure;enable<='0';wait until rising_edge(clk);wait for 0.1 ns;assert clk_out='1' report "disabled hold" severity failure;report "HDLFORGE_PASS" severity note;wait;end process;end;`
}
const allowed=new Set(Object.keys(vhdlBenches))
async function runVhdl(problemId,source){
  let dir
  try{
    dir=await mkdtemp(join(tmpdir(),'hdlforge-vhdl-'))
    const m=source.match(/\bentity\s+([A-Za-z_]\w*)\s+is\b/i)
    if(!m) return {passed:false,output:'VHDL compilation failed: no entity declaration was found.',waveform:''}
    const tb=vhdlBenches[problemId].replaceAll('{{DUT}}',m[1])
    await writeFile(join(dir,'design.vhd'),source+'\n','utf8');await writeFile(join(dir,'tb.vhd'),tb+'\n','utf8')
    for(const args of [['-a','--std=08','design.vhd'],['-a','--std=08','tb.vhd'],['-e','--std=08','tb']]) await execFileAsync('ghdl',args,{cwd:dir,timeout:TIMEOUT_MS,maxBuffer:1024*1024})
    let output='';try{const r=await execFileAsync('ghdl',['-r','--std=08','tb','--vcd=wave.vcd','--stop-time=100ns'],{cwd:dir,timeout:TIMEOUT_MS,maxBuffer:1024*1024});output=`${r.stdout}${r.stderr}`}catch(e){output=`${e.stdout||''}${e.stderr||''}${e.message||''}`}
    let waveform='';try{waveform=await readFile(join(dir,'wave.vcd'),'utf8')}catch{}
    return {passed:output.includes('HDLFORGE_PASS'),output,waveform}
  }catch(e){return {passed:false,output:`${e.stdout||''}${e.stderr||''}${e.message||''}`,waveform:''}}finally{if(dir)await rm(dir,{recursive:true,force:true}).catch(()=>{})}
}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>32768)reject(new Error('request too large'))});req.on('end',()=>{try{resolve(JSON.parse(b||'{}'))}catch(e){reject(e)}})})}
process.env.PORT=String(BACKEND_PORT)
await import('./server.js')
const proxy=http.createServer(async(req,res)=>{
  res.setHeader('Access-Control-Allow-Origin',process.env.ALLOWED_ORIGIN||'*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS')
  if(req.method==='OPTIONS')return res.writeHead(204).end()
  if(req.url==='/health')return res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({ok:true,simulators:{verilog:'verilator',vhdl:'ghdl'}}))
  if(req.method==='POST'&&(req.url==='/run'||req.url==='/interview/run')){
    try{const data=await body(req);if(data.language==='VHDL'){if(!allowed.has(data.problemId))return res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({ok:false,error:'VHDL simulation is not available for this problem yet.'}));if(typeof data.source!=='string'||data.source.length<20)return res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({ok:false,error:'Source code is required.'}));if(data.source.length>MAX_SOURCE)return res.writeHead(413,{'Content-Type':'application/json'}).end(JSON.stringify({ok:false,error:'Source code is too large.'}));const result=await runVhdl(data.problemId,data.source);return res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({ok:true,...result}))}}
    catch(e){return res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({ok:false,error:e.message||'Invalid request.'}))}
  }
  const upstream=http.request({hostname:'127.0.0.1',port:BACKEND_PORT,path:req.url,method:req.method,headers:{...req.headers,host:`127.0.0.1:${BACKEND_PORT}`}},r=>{res.writeHead(r.statusCode||502,r.headers);r.pipe(res)});upstream.on('error',e=>{res.writeHead(502,{'Content-Type':'application/json'}).end(JSON.stringify({ok:false,error:e.message}))});req.pipe(upstream)
})
proxy.listen(PORT,()=>console.log(`HDLForge GHDL proxy listening on ${PORT}`))
