const SIM_BASE = 'https://senolgulgonul.github.io/verisim/'
const MAX_SOURCE = 20000

// Existing executable RTL benches are retained; each run now also captures a VCD.
const benches = {
  'rtl-mux': `module tb; logic a,b,sel,y; mux2 dut(.a(a),.b(b),.sel(sel),.y(y)); initial begin a=0;b=0;sel=0; #1; if(y!==0) $fatal(1,"mux case 1"); a=0;b=1;sel=0; #1; if(y!==0) $fatal(1,"mux case 2"); a=0;b=1;sel=1; #1; if(y!==1) $fatal(1,"mux case 3"); a=1;b=0;sel=1; #1; if(y!==0) $fatal(1,"mux case 4"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-priority': `module tb; logic [7:0] in; logic [2:0] index; logic valid; priority_encoder dut(.in(in),.index(index),.valid(valid)); initial begin in=0; #1; if(valid!==0) $fatal(1,"zero input"); in=8'b00101000; #1; if(valid!==1 || index!==5) $fatal(1,"priority 5"); in=8'b10001000; #1; if(valid!==1 || index!==7) $fatal(1,"priority 7"); in=8'b00000001; #1; if(valid!==1 || index!==0) $fatal(1,"priority 0"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-counter': `module tb; logic clk=0,reset; logic [7:0] count; counter #(.WIDTH(8)) dut(.clk(clk),.reset(reset),.count(count)); always #1 clk=~clk; initial begin reset=1; @(posedge clk); #0.1; if(count!==0) $fatal(1,"reset"); reset=0; @(posedge clk); #0.1; if(count!==1) $fatal(1,"increment 1"); @(posedge clk); #0.1; if(count!==2) $fatal(1,"increment 2"); reset=1; @(posedge clk); #0.1; if(count!==0) $fatal(1,"second reset"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-fifo': `module tb; logic clk=0,reset,wr_en,rd_en; logic [7:0] din,dout; logic full,empty; fifo #(.WIDTH(8),.DEPTH(4)) dut(.clk(clk),.reset(reset),.wr_en(wr_en),.rd_en(rd_en),.din(din),.dout(dout),.full(full),.empty(empty)); always #1 clk=~clk; initial begin reset=1; wr_en=0; rd_en=0; din=0; @(posedge clk); #0.1; if(!empty || full) $fatal(1,"reset flags"); reset=0; din=8'hA5; wr_en=1; rd_en=0; @(posedge clk); #0.1; if(empty) $fatal(1,"empty after write"); din=8'h3C; @(posedge clk); #0.1; if(empty) $fatal(1,"empty with two entries"); wr_en=0; rd_en=1; @(posedge clk); #0.1; if(dout!==8'hA5) $fatal(1,"fifo first data"); @(posedge clk); #0.1; if(dout!==8'h3C) $fatal(1,"fifo second data"); @(posedge clk); #0.1; if(!empty) $fatal(1,"fifo not empty"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-shift-register': `module tb; logic clk=0,reset,shift_en,din; logic [7:0] dout; shift_reg #(.WIDTH(8)) dut(.clk(clk),.reset(reset),.shift_en(shift_en),.din(din),.dout(dout)); always #1 clk=~clk; initial begin reset=1; shift_en=0; din=0; @(posedge clk); #0.1; if(dout!==0) $fatal(1,"reset"); reset=0; shift_en=1; din=1; @(posedge clk); #0.1; if(dout!==8'h01) $fatal(1,"shift 1"); din=0; @(posedge clk); #0.1; if(dout!==8'h02) $fatal(1,"shift 2"); @(posedge clk); #0.1; if(dout!==8'h04) $fatal(1,"shift 3"); shift_en=0; din=1; @(posedge clk); #0.1; if(dout!==8'h04) $fatal(1,"hold"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-edge-detector': `module tb; logic clk=0,reset,signal_in,rise; edge_detector dut(.clk(clk),.reset(reset),.signal_in(signal_in),.rise(rise)); always #1 clk=~clk; initial begin reset=1; signal_in=0; @(posedge clk); #0.1; if(rise!==0) $fatal(1,"reset"); reset=0; signal_in=0; @(posedge clk); #0.1; if(rise!==0) $fatal(1,"low"); signal_in=1; @(posedge clk); #0.1; if(rise!==1) $fatal(1,"rising edge"); @(posedge clk); #0.1; if(rise!==0) $fatal(1,"held high"); signal_in=0; @(posedge clk); #0.1; if(rise!==0) $fatal(1,"falling edge"); signal_in=1; @(posedge clk); #0.1; if(rise!==1) $fatal(1,"second rising edge"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-arbiter': `module tb; logic [3:0] req,grant; arbiter4 dut(.req(req),.grant(grant)); initial begin req=0; #1; if(grant!==0) $fatal(1,"no request"); req=4'b0001; #1; if(grant!==4'b0001) $fatal(1,"request 0"); req=4'b0101; #1; if(grant!==4'b0100) $fatal(1,"priority 2"); req=4'b1011; #1; if(grant!==4'b1000) $fatal(1,"priority 3"); req=4'b0110; #1; if(grant!==4'b0100) $fatal(1,"priority 2 only"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-regfile': `module tb; logic clk=0,reset,we; logic [1:0] waddr,raddr1,raddr2; logic [7:0] wdata,rdata1,rdata2; regfile4 dut(.clk(clk),.reset(reset),.we(we),.waddr(waddr),.raddr1(raddr1),.raddr2(raddr2),.wdata(wdata),.rdata1(rdata1),.rdata2(rdata2)); always #1 clk=~clk; initial begin reset=1; we=0; waddr=0; raddr1=0; raddr2=1; wdata=0; @(posedge clk); #0.1; if(rdata1!==0 || rdata2!==0) $fatal(1,"reset clear"); reset=0; we=1; waddr=2; wdata=8'h5A; @(posedge clk); #0.1; we=0; raddr1=2; raddr2=0; #1; if(rdata1!==8'h5A || rdata2!==0) $fatal(1,"readback"); we=1; waddr=0; wdata=8'hC3; @(posedge clk); #0.1; we=0; raddr1=0; #1; if(rdata1!==8'hC3) $fatal(1,"second write"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-lfsr': `module tb; logic clk=0,reset,enable; logic [7:0] state; lfsr8 dut(.clk(clk),.reset(reset),.enable(enable),.state(state)); always #1 clk=~clk; initial begin reset=1; enable=0; @(posedge clk); #0.1; if(state!==8'h01) $fatal(1,"seed"); reset=0; enable=1; @(posedge clk); #0.1; if(state!==8'h02) $fatal(1,"lfsr step 1"); @(posedge clk); #0.1; if(state!==8'h04) $fatal(1,"lfsr step 2"); @(posedge clk); #0.1; if(state!==8'h08) $fatal(1,"lfsr step 3"); @(posedge clk); #0.1; if(state!==8'h11) $fatal(1,"lfsr step 4"); enable=0; @(posedge clk); #0.1; if(state!==8'h11) $fatal(1,"hold"); $display("HDLFORGE_PASS"); $finish; end endmodule`,
  'rtl-clock-divider': `module tb; logic clk=0,reset,enable,clk_out; clk_div #(.DIV(2)) dut(.clk(clk),.reset(reset),.enable(enable),.clk_out(clk_out)); always #1 clk=~clk; initial begin reset=1; enable=0; @(posedge clk); #0.1; if(clk_out!==0) $fatal(1,"reset"); reset=0; enable=1; @(posedge clk); #0.1; if(clk_out!==0) $fatal(1,"early toggle"); @(posedge clk); #0.1; if(clk_out!==1) $fatal(1,"first toggle"); @(posedge clk); #0.1; if(clk_out!==1) $fatal(1,"hold high"); @(posedge clk); #0.1; if(clk_out!==0) $fatal(1,"second toggle"); enable=0; @(posedge clk); #0.1; if(clk_out!==0) $fatal(1,"disabled"); $display("HDLFORGE_PASS"); $finish; end endmodule`
}

const dangerous = /\$(system|popen|fopen|fwrite|fread|fclose|fseek|rewind)\b|`include\b|`system\b/i
let modulesPromise
async function loadModules(){if(!modulesPromise){modulesPromise=Promise.all([import(/* @vite-ignore */`${SIM_BASE}ivlpp.js`),import(/* @vite-ignore */`${SIM_BASE}ivl.js`),import(/* @vite-ignore */`${SIM_BASE}vvp.js`)]).then(([a,b,c])=>({initIvlpp:a.default,initIvl:b.default,initVvp:c.default})).catch(e=>{modulesPromise=null;throw new Error(`Browser simulator could not load: ${e?.message||e}`)})}return modulesPromise}
function sanitize(source){return source.replace(/[\u00A0\u1680\u2000-\u200A\u202F\u205F\u3000]/g,' ').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[\u2018\u2019\u201A\u201B\u2032]/g,"'").replace(/[\u201C\u201D\u201E\u201F\u2033]/g,'"')}
function ivlConfig(g){return `basedir:/\nmodule:system.vpi\ngeneration:${g}\ngeneration:no-specify\nout:/out.vvp\niwidth:32\nwidthcap:65536\nfunctor:cprop\nfunctor:nodangle\nflag:DLL=vvp.tgt\n`}
async function preprocess(init,files){const out=[];const m=await init({print:t=>out.push(t),printErr:()=>{}});const args=['-L'];for(const f of files){m.FS.writeFile(`/${f.name}`,f.src.endsWith('\n')?f.src:`${f.src}\n`);args.push(`/${f.name}`)}m.callMain(args);return `${out.join('\n')}\n`}
async function compile(init,source,g){const errors=[];const m=await init({print:()=>{},printErr:t=>errors.push(t)});m.FS.writeFile('/ivl.conf',ivlConfig(g));m.FS.writeFile('/src.v',source);m.callMain(['-C/ivl.conf','--','/src.v']);let vvp=null;try{vvp=m.FS.readFile('/out.vvp')}catch{}return{vvp,errors:errors.join('\n')}}
async function simulate(init,bytes){const output=[];const m=await init({print:t=>output.push(t),printErr:t=>output.push(t)});m.FS.writeFile('/sim.vvp',bytes);m.callMain(['/sim.vvp']);let waveform='';try{waveform=new TextDecoder().decode(m.FS.readFile('/wave.vcd'))}catch{}return{output:output.join('\n'),waveform}}
export function getBrowserSimulatorProblems(){return Object.keys(benches)}
export async function runBrowserSimulation(problemId,source){if(!benches[problemId])throw new Error('This problem does not have a browser simulator testbench yet.');if(typeof source!=='string'||source.trim().length<20)throw new Error('Source code is required.');if(source.length>MAX_SOURCE)throw new Error('Source code is too large.');if(dangerous.test(source))throw new Error('This submission contains a blocked system/file operation.');const{initIvlpp,initIvl,initVvp}=await loadModules();const design=sanitize(source);const tb=benches[problemId].replace('module tb;','module tb;\ninitial begin $dumpfile("/wave.vcd"); $dumpvars(0,tb); end');const pre=await preprocess(initIvlpp,[{name:'design.sv',src:design},{name:'tb.sv',src:tb}]);const compiled=await compile(initIvl,pre,'2012');if(!compiled.vvp){const diagnostic=compiled.errors.split('\n').filter(line=>!/system\.vpi|dynamic linking not enabled/.test(line)).join('\n').trim();return{passed:false,output:diagnostic||'Compilation failed.',waveform:''}}const warnings=compiled.errors.split('\n').filter(line=>!/system\.vpi|dynamic linking not enabled/.test(line)).join('\n').trim();const sim=await simulate(initVvp,compiled.vvp);const output=[warnings,sim.output].filter(Boolean).join('\n');return{passed:output.includes('HDLFORGE_PASS'),output:output||'(no simulator output)',waveform:sim.waveform}}
