import React, { useMemo, useState } from 'react'
import { Activity, CheckCircle2, Code2, FileCode2, MessageSquare, Play, RotateCcw, Terminal, ChevronDown, ChevronUp } from 'lucide-react'
import { runBrowserSimulation } from './browserSimulator'
import './ide-overrides.css'

const RUNNER_URL = (import.meta.env.VITE_RUNNER_URL || '').replace(/\/$/, '')
const languages = ['Verilog', 'SystemVerilog', 'VHDL']
const load = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)) } catch { return fallback } }
const vhdlStarters = {
  'rtl-mux': `library ieee; use ieee.std_logic_1164.all; entity mux2 is port(a,b,sel: in std_logic; y: out std_logic); end; architecture rtl of mux2 is begin -- Your RTL here end;`,
  'rtl-counter': `library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all; entity counter is generic(WIDTH: positive:=8); port(clk,reset: in std_logic; count: out std_logic_vector(WIDTH-1 downto 0)); end; architecture rtl of counter is begin -- Your RTL here end;`,
  'rtl-priority': `library ieee; use ieee.std_logic_1164.all; entity priority_encoder is port(inp: in std_logic_vector(7 downto 0); index: out std_logic_vector(2 downto 0); valid: out std_logic); end; architecture rtl of priority_encoder is begin -- Your RTL here end;`,
  'rtl-fifo': `library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all; entity fifo is generic(WIDTH: positive:=8; DEPTH: positive:=4); port(clk,reset,wr_en,rd_en: in std_logic; din: in std_logic_vector(WIDTH-1 downto 0); dout: out std_logic_vector(WIDTH-1 downto 0); full,empty: out std_logic); end; architecture rtl of fifo is begin -- Your RTL here end;`,
  'rtl-shift-register': `library ieee; use ieee.std_logic_1164.all; entity shift_reg is generic(WIDTH: positive:=8); port(clk,reset,shift_en,din: in std_logic; dout: out std_logic_vector(WIDTH-1 downto 0)); end; architecture rtl of shift_reg is begin -- Your RTL here end;`,
  'rtl-edge-detector': `library ieee; use ieee.std_logic_1164.all; entity edge_detector is port(clk,reset,signal_in: in std_logic; rise: out std_logic); end; architecture rtl of edge_detector is begin -- Your RTL here end;`,
  'rtl-arbiter': `library ieee; use ieee.std_logic_1164.all; entity arbiter4 is port(req: in std_logic_vector(3 downto 0); grant: out std_logic_vector(3 downto 0)); end; architecture rtl of arbiter4 is begin -- Your RTL here end;`,
  'rtl-regfile': `library ieee; use ieee.std_logic_1164.all; entity regfile4 is port(clk,reset,we: in std_logic; waddr,raddr1,raddr2: in std_logic_vector(1 downto 0); wdata: in std_logic_vector(7 downto 0); rdata1,rdata2: out std_logic_vector(7 downto 0)); end; architecture rtl of regfile4 is begin -- Your RTL here end;`,
  'rtl-lfsr': `library ieee; use ieee.std_logic_1164.all; entity lfsr8 is port(clk,reset,enable: in std_logic; state: out std_logic_vector(7 downto 0)); end; architecture rtl of lfsr8 is begin -- Your RTL here end;`,
  'rtl-clock-divider': `library ieee; use ieee.std_logic_1164.all; entity clk_div is generic(DIV: positive:=2); port(clk,reset,enable: in std_logic; clk_out: out std_logic); end; architecture rtl of clk_div is begin -- Your RTL here end;`,
}
function languageStarter(problem, language) {
  if (language === 'SystemVerilog') return problem.starterCode
  if (language === 'Verilog') return problem.starterCode.replace(/\blogic\b/g, 'reg').replace(/\binput reg\b/g, 'input').replace(/\boutput reg\b/g, 'output')
  return vhdlStarters[problem.id] || `library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all; entity ${problem.id.replace(/-/g, '_')} is end; architecture rtl of ${problem.id.replace(/-/g, '_')} is begin -- Your RTL here end;`
}
function vcdParse(vcd) {
  if (!vcd) return { signals: [], end: 0 }
  const lines = vcd.split(/\r?\n/), vars = [], values = {}, times = []
  let scope = '', time = 0, started = false
  for (const raw of lines) {
    const line = raw.trim()
    if (line.startsWith('$scope')) scope = line.split(/\s+/)[2] || ''
    if (line.startsWith('$var')) { const p = line.split(/\s+/), code = p[3]; vars.push({ code, name: p[4], width: Number(p[2]) || 1, scope: scope || 'tb' }); values[code] = [] }
    if (line[0] === '#') { time = Number(line.slice(1)); times.push(time); started = true; continue }
    if (started && /^[01xXzZ][!-~]+$/.test(line)) { const code = line.slice(1); if (values[code]) values[code].push({ t: time, v: line[0].toLowerCase() }) }
    else if (started && /^b[01xXzZ]+\s+[!-~]+$/.test(line)) { const p = line.split(/\s+/); if (values[p[1]]) values[p[1]].push({ t: time, v: p[0].slice(1) }) }
  }
  const seen = new Set()
  return { signals: vars.filter(s => !seen.has(s.code) && seen.add(s.code)).map(s => ({ ...s, events: values[s.code] || [] })), end: times.at(-1) || 0 }
}
function valueLabel(value, width) { if (width <= 1) return value; if (/^[01]+$/.test(value)) return `0x${parseInt(value, 2).toString(16).toUpperCase()}`; return value.toUpperCase() }
function Waveform({ vcd }) {
  const [zoom, setZoom] = useState(1), [cursor, setCursor] = useState(null), parsed = useMemo(() => vcdParse(vcd), [vcd])
  if (!parsed.signals.length) return <div className="waveform-empty">No waveform was produced by this simulation.</div>
  const left = 120, row = 42, axis = 30, width = Math.max(760, parsed.end * 2.4 + 80) * zoom, gridStep = parsed.end > 100 ? 20 : parsed.end > 40 ? 10 : 5
  const xAt = t => left + (t / Math.max(parsed.end, 1)) * (width - left - 20)
  const digitalPath = events => {
    if (!events.length) return ''
    let d = `M ${left} 28`, previous = events[0].v
    events.forEach(event => { const x = xAt(event.t), oldY = previous === '1' ? 10 : 28, newY = event.v === '1' ? 10 : 28; d += ` L ${x} ${oldY} L ${x} ${newY}`; previous = event.v })
    return d + ` L ${xAt(parsed.end)} ${previous === '1' ? 10 : 28}`
  }
  return <div className="waveform"><div className="wave-head"><div><strong>Waveform</strong><span>Digital simulation trace · hover a transition for its timestamp</span></div><div className="wave-tools"><button title="Zoom out" onClick={() => setZoom(Math.max(.5, zoom - .25))}>−</button><span>{Math.round(zoom * 100)}%</span><button title="Zoom in" onClick={() => setZoom(Math.min(4, zoom + .25))}>+</button></div></div><div className="wave-scroll"><svg className="wave-svg" width={width} height={axis + parsed.signals.length * row} role="img" aria-label="Simulation waveform">
    {Array.from({ length: Math.floor(parsed.end / gridStep) + 1 }, (_, i) => { const t = Math.min(parsed.end, i * gridStep), x = xAt(t); return <g key={i}><line x1={x} x2={x} y1={axis} y2={axis + parsed.signals.length * row} className="wave-grid" /><text x={x + 3} y={18} className="wave-time">{t}</text></g> })}
    {parsed.signals.map((signal, index) => { const y = axis + index * row; return <g key={signal.code}><rect x="0" y={y} width={left - 1} height={row} className="wave-label-bg" /><text x="10" y={y + 19} className="wave-name">{signal.name}</text><text x="10" y={y + 33} className="wave-width">{signal.width > 1 ? `[${signal.width - 1}:0]` : '1-bit'}</text><line x1={left} x2={width} y1={y + row - 1} y2={y + row - 1} className="wave-row" />
      {signal.width === 1 ? <><path d={digitalPath(signal.events)} transform={`translate(0 ${y})`} className="wave-digital" />{signal.events.map((event, i) => <circle key={`c-${i}`} cx={xAt(event.t)} cy={y + (event.v === '1' ? 10 : 28)} r="3" className="wave-transition" onMouseEnter={() => setCursor({ signal: signal.name, time: event.t, value: event.v })} onMouseLeave={() => setCursor(null)} />)}</> : signal.events.map((event, i) => <g key={i}><rect x={xAt(event.t)} y={y + 9} width={Math.max(1, xAt(i + 1 < signal.events.length ? signal.events[i + 1].t : parsed.end) - xAt(event.t))} height={24} className="wave-bus" /><text x={xAt(event.t) + 6} y={y + 25} className="wave-bus-text">{valueLabel(event.v, signal.width)}</text></g>)}
    </g> })}<line x1={left} x2={width} y1={axis} y2={axis} className="wave-axis-line" /></svg>{cursor && <div className="wave-cursor"><strong>{cursor.signal}</strong> · t={cursor.time} · {cursor.value}</div>}</div></div>
}
function Discussion({ problem }) {
  const key = `hdlforge-discussion-${problem.id}`, [posts, setPosts] = useState(() => load(key, [])), [draft, setDraft] = useState('')
  const submit = event => { event.preventDefault(); if (!draft.trim()) return; const next = [...posts, { id: Date.now(), name: 'You', text: draft.trim(), time: new Date().toLocaleString() }]; setPosts(next); localStorage.setItem(key, JSON.stringify(next)); setDraft('') }
  return <div className="discussion discussion-in-tab"><div className="discussion-head"><div><h2>Discussion</h2><p>Ask questions, compare implementations and discuss edge cases.</p></div><span><MessageSquare size={15} /> {posts.length} posts</span></div><form className="discussion-form" onSubmit={submit}><textarea value={draft} onChange={e => setDraft(e.target.value)} placeholder="Ask a question or share an approach…" /><button className="primary">Post discussion</button></form><div className="discussion-list">{posts.length ? posts.map(post => <article className="discussion-post" key={post.id}><div className="post-avatar">Y</div><div><strong>{post.name}</strong><small>{post.time}</small><p>{post.text}</p></div></article>) : <div className="discussion-empty"><MessageSquare size={22} /><strong>Start the discussion</strong><p>Be the first to ask a question about this problem.</p></div>}</div></div>
}
function Editor({ code, language, onChange, onRun }) {
  const [showFind, setShowFind] = useState(false), [query, setQuery] = useState('')
  const handleKeyDown = e => {
    if (e.key === 'Tab') { e.preventDefault(); const el = e.currentTarget, start = el.selectionStart, end = el.selectionEnd, next = code.slice(0, start) + '  ' + code.slice(end); onChange(next); requestAnimationFrame(() => { el.selectionStart = el.selectionEnd = start + 2 }) }
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); onRun() }
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'f') { e.preventDefault(); setShowFind(true) }
  }
  const lines = code.split('\n').length
  return <div className="editor-wrap"><div className="editor-toolbar"><span>HDL source · {language}</span><div className="editor-shortcuts"><span>Tab indent</span><span>Ctrl+Enter run</span><button title="Find" onClick={() => setShowFind(v => !v)}>⌕</button></div></div>{showFind && <div className="editor-search"><span>⌕</span><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Find in source…" /><span>{query ? (code.split(query).length - 1) : 0} matches</span></div>}<div className="editor-stage"><div className="editor-gutter">{Array.from({ length: lines }, (_, i) => <span key={i}>{i + 1}</span>)}</div><textarea className="ide-editor" value={code} onChange={e => onChange(e.target.value)} onKeyDown={handleKeyDown} spellCheck="false" aria-label="HDL source editor" /></div></div>
}
export default function ProblemIDE({ problem, solved, draft, onBack, onSave, onSolved, onToggle, onPrevious, onNext, hasPrevious, hasNext }) {
  const supported = problem.languages?.length ? problem.languages : languages, evaluationType = problem.evaluation?.type || 'simulation', isConceptual = evaluationType === 'answer', initialLanguage = supported.includes('SystemVerilog') ? 'SystemVerilog' : supported[0] || 'SystemVerilog'
  const [code, setCode] = useState(draft ?? languageStarter(problem, initialLanguage)), [editorLanguage, setEditorLanguage] = useState(initialLanguage), [bottomTab, setBottomTab] = useState('console'), [result, setResult] = useState(null), [running, setRunning] = useState(false), [statementTab, setStatementTab] = useState('problem'), [bottomCollapsed, setBottomCollapsed] = useState(false), [panelSplit, setPanelSplit] = useState(38), [draggingPanel, setDraggingPanel] = useState(false)
  const update = value => { setCode(value); onSave(problem.id, value) }
  const changeLanguage = language => { setEditorLanguage(language); const next = languageStarter(problem, language); setCode(next); onSave(problem.id, next); setResult(null) }
  const run = async () => {
    if (isConceptual) { setResult({ pass: false, output: 'Automated answer evaluation is not configured for this problem yet.', waveform: null }); return }
    setRunning(true); setBottomTab('console'); setBottomCollapsed(false)
    try {
      let data
      if (editorLanguage === 'VHDL') { if (!RUNNER_URL) throw new Error('VHDL simulator is not configured. Set VITE_RUNNER_URL to the HDLForge GHDL runner.'); const response = await fetch(`${RUNNER_URL}/run`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ problemId: problem.id, source: code, language: 'VHDL' }) }); data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || 'VHDL runner failed.') }
      else data = await runBrowserSimulation(problem.id, code)
      const passed = Boolean(data.passed); setResult({ pass: passed, output: data.output || 'Simulation completed.', waveform: data.waveform }); if (passed && !solved) (onSolved || onToggle)?.(problem.id)
    } catch (error) { setResult({ pass: false, output: error?.message || 'Simulator failed.', waveform: null }) } finally { setRunning(false) }
  }
  const renderProblem = () => <div className="problem-copy"><section className="problem-section first"><div className="problem-heading" style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:'12px',padding:'20px 0 18px',borderBottom:'1px solid var(--ide-border-soft)'}}><div style={{minWidth:0}}><h1 style={{margin:0,color:'#e8eef5',fontSize:'20px',lineHeight:1.25,fontWeight:750,overflowWrap:'anywhere'}}>{problem.title}</h1><span className="problem-category" style={{display:'inline-block',marginTop:'7px',color:'#67d5ff',fontSize:'9px',fontWeight:800,letterSpacing:'.1em',textTransform:'uppercase'}}>{problem.category}</span></div><span className={`difficulty ${problem.difficulty.toLowerCase()}`}>{problem.difficulty}</span></div><h2>Task</h2><p>{problem.task}</p></section><section className="problem-section"><h2>Examples</h2><div className="examples">{problem.examples.map((example, index) => <div key={index}><span>Example {index + 1}</span><pre>{example}</pre></div>)}</div></section>{problem.constraints?.length ? <section className="problem-section"><h2>Constraints</h2><ul>{problem.constraints.map((item, index) => <li key={index}>{item}</li>)}</ul></section> : null}</div>
  const resizePanel = e => { if (!draggingPanel) return; const body = e.currentTarget.closest('.ide-body'); if (!body) return; const rect = body.getBoundingClientRect(); setPanelSplit(Math.min(65, Math.max(25, ((e.clientX - rect.left) / rect.width) * 100))) }
  return <div className="ide-page"><header className="ide-topbar"><button className="ide-brand topbar-brand" onClick={onBack} aria-label="Back to HDLForge problems" style={{flex:'0 0 auto',margin:0,padding:'7px 9px',border:'0',background:'transparent',color:'#e8eef5',cursor:'pointer'}}><span className="ide-brand-icon">HDL</span><strong>HDLForge</strong></button><div className="ide-problem-navigation topbar-navigation" style={{position:'absolute',left:'50%',transform:'translateX(-50%)'}}><button onClick={onPrevious} disabled={!hasPrevious}>← Previous</button><button className="section-navigation" onClick={onBack} aria-label={`Back to ${problem.category}`}>{problem.category}</button><button onClick={onNext} disabled={!hasNext}>Next →</button></div><div className="ide-actions">{solved ? <div className="solve-status passed"><CheckCircle2 size={15} /> {isConceptual ? 'Evaluated · Solved' : 'Tests passed · Solved'}</div> : <div className="solve-status">{isConceptual ? 'Evaluation not configured' : 'Run tests to solve'}</div>}<button className="primary" disabled={running} onClick={run}>{running ? <><Activity size={15} /> Running…</> : <><Play size={15} /> {isConceptual ? 'Evaluate' : 'Run tests'}</>}</button></div></header>
    <div className="ide-body" style={{ '--ide-panel-split': `${panelSplit}%` }} onPointerMove={resizePanel} onPointerUp={() => setDraggingPanel(false)}><aside className="ide-problem"><nav className="problem-tabs" aria-label="Problem information">{['problem', 'approach', 'solution', 'discussion'].map(tab => <button key={tab} className={statementTab === tab ? 'active' : ''} onClick={() => setStatementTab(tab)}>{tab === 'discussion' && <MessageSquare size={13} />}{tab[0].toUpperCase() + tab.slice(1)}</button>)}</nav><div className="ide-problem-content">{statementTab === 'problem' && renderProblem()}{statementTab === 'approach' && <div className="content-card"><h2>How to think about it</h2><p>{problem.approach || 'Identify inputs, outputs, timing, reset semantics and required state. Implement the simplest synthesizable solution and check corner cases.'}</p></div>}{statementTab === 'solution' && <div className="content-card"><h2>Reference solution</h2><p>Try the problem first, then inspect the reference implementation.</p><pre className="solution-code">{problem.solution || 'Reference solution will be added for this problem.'}</pre></div>}{statementTab === 'discussion' && <Discussion problem={problem} />}</div></aside><div className={`ide-panel-resizer${draggingPanel ? ' dragging' : ''}`} onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture?.(e.pointerId); setDraggingPanel(true) }} role="separator" aria-label="Resize task and editor panels" aria-valuenow={Math.round(panelSplit)}><span>⋮</span></div>
      <section className="ide-workspace"><div className="file-tabs"><div className="file-tab active"><FileCode2 size={14} /><span>{isConceptual ? 'answer.txt' : `solution.${editorLanguage === 'VHDL' ? 'vhd' : editorLanguage === 'Verilog' ? 'v' : 'sv'}`}</span></div>{!isConceptual && <><div className="editor-language"><select value={editorLanguage} onChange={e => changeLanguage(e.target.value)}>{supported.map(language => <option key={language}>{language}</option>)}</select></div><button className="icon-btn" title="Reset editor" onClick={() => changeLanguage(editorLanguage)}><RotateCcw size={14} /></button></>}</div>{isConceptual ? <div className="editor-shell"><div className="editor-gutter">{code.split('\n').map((_, i) => <span key={i}>{i + 1}</span>)}</div><textarea className="ide-editor" value={code} onChange={e => update(e.target.value)} spellCheck="false" /></div> : <Editor code={code} language={editorLanguage} onChange={update} onRun={run} />}
      <div className={`ide-bottom${bottomCollapsed ? ' collapsed' : ''}`}><div className="bottom-tabs"><button className={bottomTab === 'console' ? 'active' : ''} onClick={() => { setBottomTab('console'); setBottomCollapsed(false) }}><Terminal size={14} /> Console</button>{!isConceptual && <button className={bottomTab === 'waveform' ? 'active' : ''} onClick={() => { setBottomTab('waveform'); setBottomCollapsed(false) }}><Activity size={14} /> Waveform</button>}<button className={bottomTab === 'testbench' ? 'active' : ''} onClick={() => { setBottomTab('testbench'); setBottomCollapsed(false) }}><Code2 size={14} /> {isConceptual ? 'Evaluation' : 'Testbench'}</button><button className="bottom-collapse" title={bottomCollapsed ? 'Expand console' : 'Collapse console'} onClick={() => setBottomCollapsed(v => !v)}>{bottomCollapsed ? <ChevronUp size={14} /> : <ChevronDown size={14} />}{bottomCollapsed ? 'Expand' : 'Collapse'}</button></div>{!bottomCollapsed && <div className="console">{bottomTab === 'console' && (result ? <div className={result.pass ? 'run-result pass' : 'run-result fail'}><strong>{result.pass ? '✓ All tests passed' : isConceptual ? 'Evaluation unavailable' : '× Tests failed'}</strong><pre>{result.output}</pre></div> : <div className="console-empty"><Terminal size={18} /><span>{isConceptual ? 'Evaluation is not configured for this conceptual problem.' : 'Run the tests to see compiler and test output.'}</span></div>)}{bottomTab === 'waveform' && !isConceptual && (result?.waveform ? <Waveform vcd={result.waveform} /> : <div className="console-empty"><Activity size={18} /><span>Run a simulation to generate a waveform.</span></div>)}{bottomTab === 'testbench' && <div className="testbench-info"><strong><Code2 size={15} /> {isConceptual ? 'Evaluation' : 'Testbench'}</strong><p>{isConceptual ? 'This problem is conceptual and uses answer evaluation. Automated answer evaluation will be added with Interview Mode.' : 'HDLForge runs the problem\'s testbench against your submitted design. Hidden tests will be server-side in Interview Mode.'}</p><pre>{problem.testbench || 'The evaluator is managed by the problem harness.'}</pre></div>}</div>}</div></section></div></div>
}
