import React from 'react'
import{ArrowRight,Cpu}from'lucide-react'

const roleGroups=[
 {role:'Design Verification',summary:'Projects that demonstrate testbench architecture, constrained-random stimulus, assertions, coverage and debugging.',projects:[
  {title:'UVM Verification Environment for an AXI4-Lite Peripheral',level:'Intermediate',build:'Create an AXI4-Lite slave DUT and a reusable UVM environment with sequence items, driver, monitor, scoreboard, coverage and protocol assertions.',skills:['SystemVerilog','UVM','SVA','AXI4-Lite','Functional coverage'],deliverables:['RTL peripheral','UVM testbench','coverage report','assertion report','regression script'],why:'Shows that you can verify a realistic bus-connected block end to end.'},
  {title:'RISC-V Core Verification',level:'Advanced',build:'Verify an RV32I core using directed and constrained-random instruction streams, architectural scoreboarding, assertions and coverage across instruction classes and hazards.',skills:['RISC-V','UVM/SystemVerilog','Scoreboarding','Coverage','Assertions'],deliverables:['test plan','reference model/checker','random tests','coverage closure report'],why:'Demonstrates processor verification, debug discipline and coverage-driven thinking.'},
  {title:'APB Peripheral Verification Suite',level:'Beginner',build:'Verify GPIO, timer and register-bank peripherals behind APB with reusable agents and negative/error tests.',skills:['SystemVerilog','APB','Assertions','Scoreboards'],deliverables:['three DUTs','reusable APB agent','test matrix','regression results'],why:'A compact way to show verification fundamentals before moving to AXI or processor-level work.'}
 ]},
 {role:'RTL / Digital Design',summary:'Projects focused on synthesizable microarchitecture, pipelining, control logic and clean interfaces.',projects:[
  {title:'Three-Stage Pipelined RISC-V Core',level:'Advanced',build:'Implement an RV32I processor with fetch/decode/execute-style staging, hazard handling, forwarding or stalls, branches and a simple memory interface.',skills:['Verilog/SystemVerilog','Pipelining','Hazards','RISC-V','Microarchitecture'],deliverables:['RTL','testbench','block diagram','timing/area summary','ISA regression results'],why:'Strong evidence of RTL design, control-path reasoning and processor fundamentals.'},
  {title:'Parameterized Cache or Memory Controller',level:'Advanced',build:'Design a configurable direct-mapped or set-associative cache, or a burst-capable memory controller with refill/writeback state machines.',skills:['FSM design','Memory systems','Parameterized RTL','Performance counters'],deliverables:['RTL','self-checking tests','hit/miss measurements','design document'],why:'Shows stateful RTL beyond simple interview blocks and connects architecture to implementation.'},
  {title:'CDC-Safe Asynchronous FIFO',level:'Intermediate',build:'Implement a dual-clock FIFO using Gray-code pointers, synchronizers and full/empty detection, then verify corner cases.',skills:['CDC','Gray code','FIFO design','Reset strategy'],deliverables:['RTL','CDC explanation','testbench','assertions'],why:'Demonstrates practical clock-domain-crossing knowledge expected in many digital design roles.'}
 ]},
 {role:'FPGA',summary:'Projects that combine RTL with board-level implementation, timing closure, interfaces and observable results.',projects:[
  {title:'FPGA Packet Parser and Statistics Engine',level:'Advanced',build:'Build a streaming Ethernet-style header parser that extracts fields, classifies packets and maintains counters at one word per cycle.',skills:['Streaming RTL','Pipelining','FPGA timing','Packet processing'],deliverables:['RTL','simulation','throughput report','FPGA utilization/timing results'],why:'Shows high-throughput datapath design and implementation awareness.'},
  {title:'UART/SPI/I2C Multi-Protocol Controller',level:'Intermediate',build:'Implement configurable serial controllers with register interfaces and integrate them into a small FPGA subsystem.',skills:['UART','SPI','I2C','FSMs','FPGA integration'],deliverables:['controllers','top-level integration','board demo or simulation','documentation'],why:'Demonstrates interface design, integration and practical FPGA bring-up skills.'},
  {title:'Hardware DSP Pipeline',level:'Intermediate',build:'Implement a FIR filter, moving-average engine or fixed-point MAC pipeline with streaming valid/ready control.',skills:['DSP','Fixed point','Pipelining','Resource trade-offs'],deliverables:['RTL','Python/MATLAB reference','waveforms','timing/utilization comparison'],why:'Useful evidence for FPGA roles involving signal processing or accelerator datapaths.'}
 ]},
 {role:'SoC / Embedded Hardware',summary:'Projects that demonstrate IP integration, memory-mapped buses, peripherals and hardware/software boundaries.',projects:[
  {title:'Small RISC-V SoC',level:'Advanced',build:'Integrate a RISC-V core with ROM/RAM, GPIO, UART, timer and an APB/AXI-Lite style interconnect, then run a bare-metal program.',skills:['SoC integration','RISC-V','Bus interconnect','Memory maps','Firmware bring-up'],deliverables:['SoC RTL','address map','firmware demo','simulation logs','architecture diagram'],why:'Shows that you can move from isolated RTL blocks to a complete programmable system.'},
  {title:'AXI-Lite to APB Bridge',level:'Intermediate',build:'Design and verify a bridge that converts AXI-Lite transactions into APB transfers with correct backpressure and response handling.',skills:['AXI-Lite','APB','Protocol conversion','FSM design'],deliverables:['RTL','protocol diagrams','self-checking tests','corner-case matrix'],why:'A realistic SoC integration block that exercises protocol and control-path reasoning.'},
  {title:'DMA Engine with Register Interface',level:'Advanced',build:'Implement a memory-copy DMA with programmable source, destination and length registers, status/interrupts and burst-style transfers.',skills:['DMA','Memory-mapped control','Datapaths','Interrupts'],deliverables:['RTL','register spec','testbench','throughput measurements'],why:'Demonstrates control/datapath partitioning and common SoC subsystem concepts.'}
 ]},
 {role:'Low-Latency / HFT Hardware',summary:'Projects centered on deterministic pipelines, streaming data, latency measurement and throughput.',projects:[
  {title:'Low-Latency Market Data Parser',level:'Advanced',build:'Parse a simplified binary market-data feed into fixed-latency normalized messages with no frame buffering on the critical path.',skills:['Low-latency RTL','Streaming protocols','Pipelining','Latency measurement'],deliverables:['RTL','cycle-by-cycle latency table','self-checking feed generator','timing results'],why:'Shows the design style used for deterministic, line-rate FPGA processing without claiming any specific firm uses the exact design.'},
  {title:'Order Book Update Datapath',level:'Advanced',build:'Implement a simplified price-level table that applies add/update/delete messages and exposes best bid/ask using bounded-latency hardware structures.',skills:['Data structures in hardware','BRAM','Priority logic','Pipelining'],deliverables:['RTL','reference model','latency/throughput results','resource analysis'],why:'Demonstrates translating algorithmic state updates into deterministic hardware.'},
  {title:'Timestamped Feed-to-Action Pipeline',level:'Advanced',build:'Create a synthetic feed handler, rule engine and output-action path, timestamping stages to measure total and per-stage latency.',skills:['Latency budgeting','Pipeline design','Counters/timestamps','Verification'],deliverables:['RTL','latency histogram/table','testbench','critical-path discussion'],why:'Makes latency engineering measurable and gives you a strong artifact to discuss in FPGA/HFT interviews.'}
 ]}
]

export default function Projects({onStartRiscv}){return <div className="projects-page"><div className="page-head"><div className="eyebrow">PORTFOLIO PROJECTS</div><h1>Projects for hardware roles</h1><p>Build substantial projects that give you concrete RTL, verification, FPGA and architecture work to discuss in applications and interviews.</p></div><section className="guided-project"><div className="guided-project-icon"><Cpu size={28}/></div><div className="guided-project-copy"><div><span className="project-level">GUIDED · BEGINNER TO INTERMEDIATE</span><span className="guided-time">8 stages · ~2.5 hours</span></div><h2>Build a 32-bit RISC-V CPU core</h2><p>Go from an empty datapath to a working RV32I single-cycle core. Write SystemVerilog beside each lesson, pass focused checks, and unlock the next stage.</p><div className="project-tags"><span>RV32I</span><span>SystemVerilog</span><span>CPU architecture</span><span>Interactive lab</span></div></div><button className="guided-start" onClick={onStartRiscv}>Start building <ArrowRight size={16}/></button></section>{roleGroups.map(group=><section className="project-role" key={group.role}><div className="project-role-head"><h2>{group.role}</h2><p>{group.summary}</p></div><div className="project-grid">{group.projects.map(project=><article className="project-card" key={project.title}><div className="project-card-top"><span className="project-level">{project.level}</span><h3>{project.title}</h3></div><p className="project-build"><strong>Build:</strong> {project.build}</p><div><strong>Key skills</strong><div className="project-tags">{project.skills.map(skill=><span key={skill}>{skill}</span>)}</div></div><div><strong>Suggested deliverables</strong><ul>{project.deliverables.map(item=><li key={item}>{item}</li>)}</ul></div><p className="project-why"><strong>Why it helps:</strong> {project.why}</p></article>)}</div></section>)}</div>}
