import React from 'react'
import{ArrowRight,Cpu}from'lucide-react'
import {guidedProject,roleGroups} from './data/projects'
import {riscvProject} from './data/riscvProject'

export default function Projects({onStartRiscv,solved=[]}){
 const completed=riscvProject.problemIds.filter(id=>solved.includes(id)).length
 const action=completed===0?'Start project':completed===riscvProject.problemIds.length?'Review project':'Continue project'
 return <div className="projects-page"><div className="page-head"><div className="eyebrow">PORTFOLIO PROJECTS</div><h1>Hardware design projects</h1><p>Build substantial RTL, verification, FPGA and architecture projects that give you concrete work to discuss in applications and interviews.</p></div><section className="guided-project guided-project-clickable" role="button" tabIndex={0} onClick={onStartRiscv} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onStartRiscv()}}} aria-label={`${action}: ${riscvProject.title}`}><div className="guided-project-icon"><Cpu size={28}/></div><div className="guided-project-copy"><div><span className="project-level">GUIDED · {guidedProject.level.toUpperCase()}</span><span className="guided-time">{completed}/{riscvProject.problemIds.length} blocks complete</span></div><h2>{riscvProject.title}</h2><p>{guidedProject.build}</p><div className="project-tags">{guidedProject.skills.slice(0,4).map(skill=><span key={skill}>{skill}</span>)}</div></div><span className="guided-start">{action} <ArrowRight size={16}/></span></section>{roleGroups.map(group=><section className="project-role" key={group.role}><div className="project-role-head"><h2>{group.role}</h2><p>{group.summary}</p></div><div className="project-grid">{group.projects.map(project=><article className="project-card" key={project.slug}><div className="project-card-top"><span className="project-level">{project.level}</span><h3>{project.title}</h3></div><p className="project-build"><strong>Build:</strong> {project.build}</p><div><strong>Key skills</strong><div className="project-tags">{project.skills.map(skill=><span key={skill}>{skill}</span>)}</div></div><div><strong>Suggested deliverables</strong><ul>{project.deliverables.map(item=><li key={item}>{item}</li>)}</ul></div><p className="project-why"><strong>Why it helps:</strong> {project.why}</p><a href={`/projects/${project.slug}/`}>Project guide</a></article>)}</div></section>)}</div>
}
